<?php

namespace AppBundle\Repository;

use AppBundle\Entity\SellOrder;

/**
 * SellOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellOrderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $product
     * @param string $brand
     * @param double $minPrice
     * @param double $maxPrice
     * @return SellOrder[]
     */
    public function findByProductAndBrandAndPriceRange($product, $brand, $minPrice, $maxPrice)
    {
        $qb = $this->createQueryBuilder('o')
            ->select(['o', 'u'])
            ->join('o.user', 'u')
            ->andWhere('o.product = :product')
            ->andWhere('o.brand = :brand')
            ->andWhere('o.price >= :minPrice')
            ->andWhere('o.price <= :maxPrice')
            ->setParameters([
                'product' => $product,
                'brand' => $brand,
                'minPrice' => $minPrice,
                'maxPrice' => $maxPrice,
            ])
        ;

        return $qb->getQuery()->getResult();
    }
}
